name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Install Windows SDK and WDK
        run: |
          choco install windows-sdk-10-version-1903-all -y
          choco install windowsdriverkit10 -y

      - name: Build solution
        run: msbuild FileController.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: FileController
          path: x64/Release/FileController.exe

      - name: Upload driver package
        uses: actions/upload-artifact@v4
        with:
          name: FileControllerDriver
          path: x64/Release/FileControllerDriver/*

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: DebugSymbols
          path: x64/Release/FileController.pdb

      - name: Get commit hash and timestamp
        id: version_info
        run: |
          echo "timestamp=$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" >> $env:GITHUB_ENV
          echo "commit_hash=${{ github.sha }}" >> $env:GITHUB_ENV

      - name: Create or update pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          body: "Timestamp: ${{ env.timestamp }}\nCommit: ${{ env.commit_hash }}"
          draft: false
          prerelease: true
          files: |
            x64/Release/FileController.exe
            x64/Release/FileController.pdb
            x64/Release/FileControllerDriver/*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
